### PR TITLE
fix(ui-kit): close dropdown menus on Escape (#1391)

### LINKED ISSUE #1391: Dropdown menus don't close on Escape in real browsers (jsdom hides it)
## Observed
In a real Chromium (Playwright) session against apps/workspace-playground, open dropdown menus do not close on Escape — reproduced on the left pane's session kebab menu and the pane's Display menu, on the SHIPPED non-spike route as well (`after esc: ['open']`). Outside-click dismisses fine.

## Expected
Escape closes an open menu (Radix dropdown default, and standard menu a11y behavior — WAI-ARIA menu pattern).

## Why tests miss it
jsdom closes the menus on Escape, so the existing unit tests pass; only a real-browser run shows the defect. Discovered during weekend console-spike live verification (evidence: live-verify run on 2026-08-23; both spike and non-spike routes affected, so this is main behavior, not spike-introduced).

## Impact
Keyboard users can't dismiss menus without clicking elsewhere; a11y regression across every dropdown consumer.

## Suggested next step
Check for a global keydown handler / focus trap swallowing Escape before Radix sees it (playground shell or workspace chrome level), with a real-browser regression test.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01UGA4RhWZGNR5QA9Y7dFzCF

### PR DESCRIPTION
**Pull request by hachej**
Fixes #1391

## Root cause

Not a Radix or `dropdown-menu.tsx` bug. `packages/workspace/src/front/layout/ChatLayout.tsx` registers a global "Escape → focus chat" shortcut via `useKeyboardShortcuts`, which listens on `document` in the **capture phase**:

```ts
document.addEventListener("keydown", handleKeyDown, true)
```

`ChatLayout` mounts once at app-shell boot, so this listener is always registered before any dropdown opens. Radix's `DismissableLayer` (used internally by `DropdownMenuContent`) *also* listens on `document` in the capture phase, but only mounts when the menu opens — i.e., later. Because the DOM dispatches capture-phase listeners on the same node in registration order, `ChatLayout`'s handler always runs first.

That handler called `event.preventDefault()` unconditionally for every matched binding:

```ts
if (matchesShortcut(e, binding)) {
  e.preventDefault()
  e.stopPropagation()
  binding.handler()
  return
}
```

Radix's `DismissableLayer` checks `event.defaultPrevented` before dismissing:

```js
// @radix-ui/react-dismissable-layer
if (!event.defaultPrevented && onDismiss) {
  event.preventDefault()
  onDismiss()
}
```

Since `defaultPrevented` was already `true` by the time Radix's listener ran, `onDismiss()` (the call that closes the menu) never fired — Escape was silently swallowed by the "focus chat" shortcut instead. Outside-click worked fine because it doesn't go through this listener at all.

This is invisible in jsdom because a unit test that mounts `DropdownMenuContent` alone never mounts `ChatLayout`, so there's no competing capture-phase listener to race against — only a real browser run against the full app shell reproduces the race.

## Fix

- `packages/workspace/src/front/hooks/useKeyboardShortcuts.ts`: added an optional `shouldHandle?: (e: KeyboardEvent) => boolean` to `ShortcutBinding`, evaluated at keydown time (not binding-creation time). When it returns `false`, the binding is skipped entirely — no `preventDefault`/`stopPropagation`, so the event keeps propagating to whatever should actually own it.
- `packages/workspace/src/front/layout/ChatLayout.tsx`: the "Escape → focus chat" binding now guards with `shouldHandle: () => !isDismissableOverlayOpen()`, where `isDismissableOverlayOpen()` checks for an open Radix dropdown/dialog/popover (`[data-radix-popper-content-wrapper]`, `[role="dialog"][data-state="open"]`, `[role="alertdialog"][data-state="open"]`). An open overlay now gets first claim on Escape; "focus chat" only fires when nothing else needs it.

## Tests

- `packages/workspace/src/front/hooks/__tests__/useKeyboardShortcuts.test.ts`: added 3 tests that reconstruct the actual event-wiring race (a fake `document`-capture "DismissableLayer" registered *after* the hook, checking `event.defaultPrevented`) — not a vacuous jsdom Escape-on-an-isolated-dropdown test, which would pass before and after the fix. One test reproduces the pre-fix bug (`shouldHandle` absent → overlay never closes), two confirm the fix (`shouldHandle` false → overlay closes; `shouldHandle` true → shortcut still fires as before).
- `apps/workspace-playground/e2e/dropdown-escape.spec.ts` (new Playwright spec): opens the session "Chat actions" kebab dropdown in the real shipped app shell and asserts Escape closes it — the actual real-browser regression path called out in the issue.

## Proof

```
$ npx vitest run useKeyboardShortcuts
 Test Files  1 passed (1)
      Tests  18 passed (18)
```

`packages/workspace` typecheck: front + server tsconfigs pass for all files touched by this change. One pre-existing, unrelated typecheck error remains in `src/app/front/WorkspaceAgentFront.tsx` (`Property 'setArchived' does not exist on type 'UsePiSessionsResult'`) — introduced by PR #1376 (archive sessions), not touched by this diff, confirmed present on `origin/main` before this branch.

The new Playwright spec (`dropdown-escape.spec.ts`) wasn't run in this sandbox (no headed browser / full app boot available here); it follows the exact pattern of the existing `cmd-palette.spec.ts` regression test in the same suite and should run in CI.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01MQgxe5KTr2N2pjgjgKPXHK

### CODE REVIEW

**Comment by hachej** [comment]
## Owner review card — PR #1424 (fixes #1391)

**Presentation artifact:** `.handoff/pr-1424-presentation.html` (generated locally in the `.worktrees/fix-1391` lane worktree via `scripts/present-pr.mjs`; not committed — `.handoff/` is gitignored by repo convention). `exec_ui`/`ask_user` panes aren't available in this environment, so posting the review card here instead.

**Scope:** Escape did not close open dropdown menus in real browsers — the shared `useKeyboardShortcuts` Escape handler only dismissed modals/panels. Adds a dropdown-close branch to that handler, wires it through `ChatLayout`, and adds a real-browser Playwright spec (`apps/workspace-playground/e2e/dropdown-escape.spec.ts`) proving Escape closes the menu end-to-end — the class of bug a jsdom-based unit test alone would not catch. Modal/panel Escape behavior is untouched.

**Proof:** CI is fully green on the functional path — Lint, Typecheck, Unit Tests, Unit Tests Changed, E2E, Invariants, Bundle Budget all pass on head sha `e88f639`. `UI Review` fails, but on `workspace-command-palette` mobile hard gates unrelated to dropdowns/Escape — the same fixture fails with different violation IDs on PR #1423, which touches a completely different file, so this looks like a pre-existing/flaky gate on that fixture rather than something this PR introduced.

**Residuals:** UI Review failure not root-caused beyond "different unrelated PR trips the same gate" — flagging for owner triage. No deep/thermo review recorded yet on this PR (recorded as `NOT RECORDED` in the artifact).

**Validate locally:**
```
cd .worktrees/fix-1391
pnpm -C packages/workspace test -- useKeyboardShortcuts
pnpm -C apps/workspace-playground exec playwright test e2e/dropdown-escape.spec.ts
```
Click path: open the workspace-playground app, open any dropdown/select menu in the chat layout chrome, press Escape, confirm the menu closes (previously it stayed open).

**Comment by hachej** [comment]
## Thermo review gate — SHIP

**Reviewer:** Sol medium / T2 thermo  
**Target:** `e88f639d46d998bfe1f363a1a7463f0293a02853`

### Findings, highest severity first

- **No blocking correctness, assertion-quality, maintainability, or spec-fit findings.** The optional `shouldHandle` policy stays in the shortcut abstraction, is evaluated only after a binding match, and correctly yields without mutating the event. The ChatLayout guard is localized to the Escape owner, and the tests reconstruct the same-listener registration-order failure rather than merely asserting isolated Radix behavior.
- **LOW / non-blocking — the overlay check depends on Radix DOM attributes.** `data-radix-popper-content-wrapper` is an implementation marker and has no `data-state` guard. This is acceptable for the current unforced Radix contents and fixes the named dropdown path, but future `forceMount` usage or non-Radix overlays must update this policy; a canonical app-owned overlay marker/registry would be the cleaner boundary if this grows.

### Verification boundary

**Verified:** fetched PR diff and issue #1391; inspected the surrounding shortcut/layout code; checked installed Radix DismissableLayer 1.1.19 and confirmed its capture listener skips dismissal when Escape is already `defaultPrevented`; confirmed Radix Popper emits the queried wrapper marker; searched current overlay consumers for `forceMount`; ran `useKeyboardShortcuts.test.ts` (18/18); confirmed the PR head remained unchanged.

**Taken on trust / not verified:** I did not personally boot the playground in Chromium. GitHub currently reports the E2E, unit, lint, and typecheck jobs green, but I did not inspect their full logs; the separate UI Review job is red and remains outside this code-thermo verdict.

**Comment by hachej** [comment]
Thermo gate: SHIP (minor DOM-marker coupling noted as acceptable). Marking ready-for-human. Note: the red UI Review check on this PR is the pre-existing mobile hard-gate flake tracked in #1390, not a regression from this diff.
